import type { Metadata } from "next";
import BurgerMenu from "./components/BurgerMenu/BurgerMenu";
import "./globals.css";
import { BrownSectionProvider } from "./contexts/BrownSectionContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BrownSectionProvider>
          <BurgerMenu />

          {children}
        </BrownSectionProvider>
      </body>
    </html>
  );
}
